<%@ Page Title="" Language="C#" MasterPageFile="~/placementmaster.master" AutoEventWireup="true"
    CodeFile="placementdetails.aspx.cs" Inherits="_Default" %>

<asp:Content ID="Content1" ContentPlaceHolderID="bodyContent" runat="Server">
    <table>
        <tr>
            <td colspan="4" style="text-decoration: underline">
                Placed Student
            </td>
        </tr>
        <tr>
            <td>
                Year
            </td>
            <td>
                Company
            </td>
            <td>
                No. of Student Placed
            </td>
            <td>
                Branch
            </td>
        </tr>
        <tr>
            <td>
                2010
            </td>
            <td>
                Microsoft
            </td>
            <td>
                12
            </td>
            <td>
                CS/IT
            </td>
        </tr>
        <tr>
            <td>
                2010
            </td>
            <td>
                Microsoft
            </td>
            <td>
                12
            </td>
            <td>
                CS/IT
            </td>
        </tr>
        <tr>
            <td>
                2010
            </td>
            <td>
                Microsoft
            </td>
            <td>
                12
            </td>
            <td>
                CS/IT
            </td>
        </tr>
        <tr>
            <td>
                2010
            </td>
            <td>
                Microsoft
            </td>
            <td>
                12
            </td>
            <td>
                CS/IT
            </td>

        </tr>
        <tr>
            <td>
                2010
            </td>
            <td>
                Microsoft
            </td>
            <td>
                12
            </td>
            <td>
                CS/IT
            </td>
        </tr>
        <tr>
            <td>
                2010
            </td>
            <td>
                Microsoft
            </td>
            <td>
                12
            </td>
            <td>
                CS/IT
            </td>
        </tr>
        <tr>
            <td>
                2010
            </td>
            <td>
                Microsoft
            </td>
            <td>
                12
            </td>
            <td>
                CS/IT
            </td>
        </tr>
        <tr>
            <td>
                2010
            </td>
            <td>
                Microsoft
            </td>
            <td>
                12
            </td>
            <td>
                CS/IT
            </td>
        </tr>
        <tr>
            <td>
                2010
            </td>
            <td>
                Microsoft
            </td>
            <td>
                12
            </td>
            <td>
                CS/IT
            </td>
        </tr>
    </table>
</asp:Content>
